

mongoHost: localhost
mongoPortNumber: 27017
mongoDatabaseName: moves1
documentFolder: documents
baseUrl: http://localhost:8083
#authExpiry: 180000000000


# Server port number specifications
server:
  applicationConnectors:
  - type: http
    port: 8083
  adminConnectors:
  - type: http
    port: 8084

swagger:
  resourcePackage: com.moves.movesCelebrity.resources

authExpiry: 108000

#mail service details
mailerAddress: dxtestuser@gmail.com
mailerPassword: Dx@1#T3st3R
mailServiceHost: smtp.gmail.com
mailServicePort: 465
mailServiceFactoryClass: javax.net.ssl.SSLSocketFactory
mailServiceAuth: true