

mongoHost: localhost
mongoPortNumber: 27017
mongoDatabaseName: moves
documentFolder: documents
baseUrl: http://localhost:8083
#authExpiry: 86400000


# Server port number specifications
server:
  applicationConnectors:
  - type: http
    port: 8083
  adminConnectors:
  - type: http
    port: 8084

swagger:
  resourcePackage: com.moves.movesCelebrity.resources



