mongoHost: localhost
mongoPortNumber: 27017
mongoDatabaseName: moves
documentFolder: documents
baseUrl: http://localhost:8000


# Server port number specifications
server:
  applicationConnectors:
  - type: http
    port: 8000
  adminConnectors:
  - type: http
    port: 8001

swagger:
  resourcePackage: com.moves.movesCelebrity.resources